export const SET_AUTH_LOGIN = "SET_AUTH_LOGIN";
export const SET_AUTH_USER_DATA = "SET_AUTH_USER_DATA";
export const SET_AUTH_REGISTER = "SET_AUTH_REGISTER";
export const SET_AUTH_USER_TOKEN = "SET_AUTH_USER_TOKEN";
export const SET_ERROR = "SET_ERROR";

export const CLEAR_ERROR = "CLEAR_ERROR";