export const SET_AUTH_LOGIN = "SET_AUTH_LOGIN";
export const SET_AUTH_USER_DATA = "SET_AUTH_USER_DATA";
export const SET_AUTH_REGISTER = "SET_AUTH_REGISTER";
export const SET_AUTH_USER_TOKEN = "SET_AUTH_USER_TOKEN";
export const SET_ERROR = "SET_ERROR";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_AUTH_USER_ANIMAL = "SET_AUTH_USER_ANIMAL";

export const EDIT_AUTH_USER_DATA = "EDIT_AUTH_USER_DATA";

export const DONE_LOGOUT = "DONE_LOGOUT";

export const CLEAR_ERROR = "CLEAR_ERROR";